### ISSUE TITLE
用YUCIColorLookup处理的LUT效果普遍偏黑

### ISSUE THREAD

**Issue by cleexiang** [YuAo/Vivid#5]
为什么我用YUCIColorLookup处理的LUT效果普遍偏黑呢？对LUT文件有没有什么要求？

**Comment by YuAo** [comment]
要设置`kCIContextWorkingColorSpace`和LUT图的ColorSpace一致。你可以设置成DeviceRGB(`CGColorSpaceCreateDeviceRGB`)试试。
