### ISSUE TITLE
is this repo will be replaced by MetalPetal?

### ISSUE THREAD

**Issue by notedit** [YuAo/Vivid#7]
i see your another repo https://github.com/MetalPetal/MetalPetal,  they seems do the same thing.

**Comment by YuAo** [comment]
No. This is a collection of Core Image filters, while MetalPetal utilizes the power of GPU via Metal. MetalPetal is designed to work with Core Image. You can use CIImage to create a MTIImage or render a MTIImage to a CIImage. In this way, you can use Vivid along with MetalPetal.
